name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.x
    - run: dotnet build
      working-directory: ./src
    - name: Ensure browsers are installed
      run: pwsh ./src/DummyApp.UiTests/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run your tests
      working-directory: ./src
      run: dotnet test
